In [1]:
import numpy as np

In [4]:
int(np.ceil(4.9))

5

In [5]:
from astropy import units as u

In [6]:
u.Quantity(1, "cm") + u.Quantity(2, "cm")

<Quantity 3. cm>

In [1]:
arr = [1,2,3,4]
arr[1:4]

[2, 3, 4]

In [4]:
a = 2

if (a < 1):
    print ("aa")
elif (a < 3):
    print ("bb")

bb


In [8]:
import numpy as np

# 假設你的 3D np array 是這樣的
array = np.random.random((200, 200, 200))
0
# 計算每個索引位置與 (5, 5, 5) 的距離
x, y, z = np.indices(array.shape)
distances = np.sqrt((x - 5)**2 + (y - 5)**2 + (z - 5)**2)

# 找出距離小於 4 的位置
mask = distances < 80

# 選出這些位置的元素
result = array[mask]

print(result.shape)

(358033,)


In [10]:
import numpy as np
import astropy.units as u
from astropy.units import Quantity

# 假設你的 3D Quantity array 是這樣的
array = np.random.random((200, 200, 200)) * u.m

# 計算每個索引位置與 (5, 5, 5) 的距離
x, y, z = np.indices(array.shape)
coordinates = Quantity((x, y, z), unit=u.dimensionless_unscaled)
target = Quantity((100, 100, 100), unit=u.dimensionless_unscaled)

# 計算距離，並轉換為無量綱數值以便進行比較
distances = np.sqrt(((coordinates[0] - target[0])**2 + 
                     (coordinates[1] - target[1])**2 + 
                     (coordinates[2] - target[2])**2)) * u.dimensionless_unscaled

# 找出距離小於 4 單位的索引
mask = distances < 80

# 選出這些位置的元素
result = array[mask]

result

<Quantity [0.73688831, 0.74673847, 0.94725131, ..., 0.54052157, 0.21949995,
           0.87264885] m>

In [13]:
type(array)

astropy.units.quantity.Quantity

In [3]:
import numpy as np
from astropy import units as u

# 假設 3D array 的形狀為 (4, 4, 4)
shape = (200, 200, 200)

# 建立 value array，假設單位為 m
value = np.random.random(shape) * u.m

# 建立 coor array，假設單位為 m
# 為了簡單起見，這裡用隨機數來生成坐標
coor_x = np.random.random(shape)*200 * u.m
coor_y = np.random.random(shape)*200 * u.m
coor_z = np.random.random(shape)*200 * u.m
coor = np.stack([coor_x, coor_y, coor_z], axis=-1)

print("Value array:")
print(value)
print("\nCoordinate array:")
print(coor)

# 計算到原點的距離
distances = np.sqrt((coor ** 2).sum(axis=-1))

# 定義距離範圍的 bin
max_distance = np.max(distances.value) + 1  # 確保包含最大值
distance_bins = np.arange(0, max_distance, 1) * distances.unit

# 使用 np.digitize 將距離分到不同的 bin 中
bin_indices = np.digitize(distances.value, distance_bins.value)

# 創建儲存每個 bin 中 value 的列表
binned_values = []
bin_ranges = []

for i in range(1, len(distance_bins)):
    bin_mask = bin_indices == i
    if np.any(bin_mask):
        binned_values.append(value[bin_mask])
        bin_ranges.append((distance_bins[i-1], distance_bins[i]))

# 合併所有分組的 value 成一個 1D 的 Quantity
binned_values = u.Quantity(np.concatenate(binned_values))

print("\nBinned values:")
print(binned_values)

print("\nBin ranges and corresponding values:")
for bin_range, values in zip(bin_ranges, binned_values):
    print(f"Range {bin_range[0]} to {bin_range[1]}: {values}")

Value array:
[[[0.25738852 0.93825801 0.51919619 ... 0.17318809 0.10785529 0.65249746]
  [0.58867315 0.53485328 0.71586734 ... 0.251037   0.78798673 0.4150238 ]
  [0.78653644 0.59147229 0.53123827 ... 0.10504434 0.70701075 0.65536765]
  ...
  [0.44898543 0.57562533 0.81226087 ... 0.21929634 0.54516977 0.8813713 ]
  [0.32649367 0.63576344 0.17546694 ... 0.5189098  0.7449266  0.64085976]
  [0.41506865 0.14162235 0.28180862 ... 0.34980018 0.37176503 0.0718928 ]]

 [[0.74554267 0.60666015 0.74352292 ... 0.69628956 0.04216688 0.69927896]
  [0.11949326 0.08755442 0.8826856  ... 0.28622484 0.8506826  0.09356702]
  [0.72767745 0.26494724 0.20870209 ... 0.99793947 0.44605759 0.73266064]
  ...
  [0.25830078 0.71052083 0.43553277 ... 0.1643984  0.90488306 0.10426549]
  [0.57684884 0.92151619 0.43447361 ... 0.18265942 0.10753484 0.47276105]
  [0.42291785 0.50806928 0.48526096 ... 0.19809864 0.08479662 0.14856071]]

 [[0.5771521  0.79250477 0.93073379 ... 0.81453454 0.26996497 0.16410009]
  [0.0072

In [1]:
import numpy as np
from astropy import units as u

In [9]:
arr1 = np.array([1,2,3,4,7])* u.m
arr2 = np.array([4,5,6])* u.m

(arr1[1:] - arr1[:-1])/2

<Quantity [0.5, 0.5, 0.5, 1.5] m>

In [32]:
import numpy as np
from astropy import units as u

# 假設你的1D array是這樣的
points = np.array([0, 1, 2]) * u.m

# 生成網格
X, Y, Z = np.meshgrid(points, points, points, indexing="ij")

X

<Quantity [[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[2., 2., 2.],
            [2., 2., 2.],
            [2., 2., 2.]]] m>